; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\JitenderN\REBook\Array\Array\Array.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG4682	DB	'iArray[%d]=%d', 0aH, 00H
CONST	ENDS
PUBLIC	__$ArrayPad$
PUBLIC	_main
EXTRN	_printf:PROC
EXTRN	___security_cookie:DWORD
EXTRN	@__security_check_cookie@4:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_iArray$ = -48						; size = 40
__$ArrayPad$ = -8					; size = 4
_iLoop$ = -4						; size = 4
_main	PROC
; File c:\jitendern\rebook\array\array\array.cpp
; Line 7
	push	ebp
	mov	ebp, esp
	sub	esp, 48					; 00000030H
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
; Line 8
	mov	DWORD PTR _iArray$[ebp], 0
	mov	DWORD PTR _iArray$[ebp+4], 1
	mov	DWORD PTR _iArray$[ebp+8], 2
	mov	DWORD PTR _iArray$[ebp+12], 3
	mov	DWORD PTR _iArray$[ebp+16], 4
	mov	DWORD PTR _iArray$[ebp+20], 5
	mov	DWORD PTR _iArray$[ebp+24], 6
	mov	DWORD PTR _iArray$[ebp+28], 7
	mov	DWORD PTR _iArray$[ebp+32], 8
	mov	DWORD PTR _iArray$[ebp+36], 9
; Line 11
	mov	DWORD PTR _iLoop$[ebp], 0
	jmp	SHORT $LN3@main
$LN2@main:
	mov	eax, DWORD PTR _iLoop$[ebp]
	add	eax, 1
	mov	DWORD PTR _iLoop$[ebp], eax
$LN3@main:
	cmp	DWORD PTR _iLoop$[ebp], 10		; 0000000aH
	jge	SHORT $LN1@main
; Line 12
	mov	ecx, DWORD PTR _iLoop$[ebp]
	mov	edx, DWORD PTR _iArray$[ebp+ecx*4]
	push	edx
	mov	eax, DWORD PTR _iLoop$[ebp]
	push	eax
	push	OFFSET $SG4682
	call	_printf
	add	esp, 12					; 0000000cH
	jmp	SHORT $LN2@main
$LN1@main:
; Line 14
	xor	eax, eax
; Line 15
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
