; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\JitenderN\REBook\Array\Array\Array.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG4682	DB	'iArray[%d]=%d', 0aH, 00H
CONST	ENDS
PUBLIC	__$ArrayPad$
PUBLIC	_main
EXTRN	_printf:PROC
EXTRN	___security_cookie:DWORD
EXTRN	@__security_check_cookie@4:PROC
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_iArray$ = -44						; size = 40
__$ArrayPad$ = -4					; size = 4
_main	PROC
; File c:\jitendern\rebook\array\array\array.cpp
; Line 7
	sub	esp, 44					; 0000002cH
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+44], eax
	push	esi
; Line 8
	xor	esi, esi
	mov	DWORD PTR _iArray$[esp+48], esi
	mov	DWORD PTR _iArray$[esp+52], 1
	mov	DWORD PTR _iArray$[esp+56], 2
	mov	DWORD PTR _iArray$[esp+60], 3
	mov	DWORD PTR _iArray$[esp+64], 4
	mov	DWORD PTR _iArray$[esp+68], 5
	mov	DWORD PTR _iArray$[esp+72], 6
	mov	DWORD PTR _iArray$[esp+76], 7
	mov	DWORD PTR _iArray$[esp+80], 8
	mov	DWORD PTR _iArray$[esp+84], 9
	npad	3
$LL3@main:
; Line 12
	mov	eax, DWORD PTR _iArray$[esp+esi*4+48]
	push	eax
	push	esi
	push	OFFSET $SG4682
	call	_printf
	inc	esi
	add	esp, 12					; 0000000cH
	cmp	esi, 10					; 0000000aH
	jl	SHORT $LL3@main
; Line 15
	mov	ecx, DWORD PTR __$ArrayPad$[esp+48]
	pop	esi
	xor	ecx, esp
	xor	eax, eax
	call	@__security_check_cookie@4
	add	esp, 44					; 0000002cH
	ret	0
_main	ENDP
_TEXT	ENDS
END
