; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\JitenderN\REBook\CrackMe\CrackMe\CrackMe.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG4679	DB	'yyy0kke{dgtugewtkv{0eqo', 00H
CONST	ENDS
PUBLIC	__$ArrayPad$
PUBLIC	_main
EXTRN	___security_cookie:DWORD
EXTRN	@__security_check_cookie@4:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_encurl$ = -60						; size = 50
__$ArrayPad$ = -8					; size = 4
_i$ = -4						; size = 4
_main	PROC
; File c:\jitendern\rebook\crackme\crackme\crackme.cpp
; Line 9
	push	ebp
	mov	ebp, esp
	sub	esp, 60					; 0000003cH
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
; Line 11
	mov	eax, DWORD PTR $SG4679
	mov	DWORD PTR _encurl$[ebp], eax
	mov	ecx, DWORD PTR $SG4679+4
	mov	DWORD PTR _encurl$[ebp+4], ecx
	mov	edx, DWORD PTR $SG4679+8
	mov	DWORD PTR _encurl$[ebp+8], edx
	mov	eax, DWORD PTR $SG4679+12
	mov	DWORD PTR _encurl$[ebp+12], eax
	mov	ecx, DWORD PTR $SG4679+16
	mov	DWORD PTR _encurl$[ebp+16], ecx
	mov	edx, DWORD PTR $SG4679+20
	mov	DWORD PTR _encurl$[ebp+20], edx
	xor	eax, eax
	mov	DWORD PTR _encurl$[ebp+24], eax
	mov	DWORD PTR _encurl$[ebp+28], eax
	mov	DWORD PTR _encurl$[ebp+32], eax
	mov	DWORD PTR _encurl$[ebp+36], eax
	mov	DWORD PTR _encurl$[ebp+40], eax
	mov	DWORD PTR _encurl$[ebp+44], eax
	mov	WORD PTR _encurl$[ebp+48], ax
; Line 13
	mov	DWORD PTR _i$[ebp], 0
	jmp	SHORT $LN3@main
$LN2@main:
	mov	ecx, DWORD PTR _i$[ebp]
	add	ecx, 1
	mov	DWORD PTR _i$[ebp], ecx
$LN3@main:
	cmp	DWORD PTR _i$[ebp], 50			; 00000032H
	jge	SHORT $LN1@main
	mov	edx, DWORD PTR _i$[ebp]
	movsx	eax, BYTE PTR _encurl$[ebp+edx]
	test	eax, eax
	je	SHORT $LN1@main
; Line 14
	mov	ecx, DWORD PTR _i$[ebp]
	movsx	edx, BYTE PTR _encurl$[ebp+ecx]
	sub	edx, 2
	mov	eax, DWORD PTR _i$[ebp]
	mov	BYTE PTR _encurl$[ebp+eax], dl
	jmp	SHORT $LN2@main
$LN1@main:
; Line 16
	xor	eax, eax
; Line 17
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
