; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\JitenderN\REBook\AddNumber\AddNumber\AddNumber.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?addition@@YIHHH@Z				; addition
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_add$ = -4						; size = 4
_main	PROC
; File c:\jitendern\rebook\addnumber\addnumber\addnumber.cpp
; Line 10
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 12
	mov	edx, 5
	mov	ecx, 4
	call	?addition@@YIHHH@Z			; addition
	mov	DWORD PTR _add$[ebp], eax
; Line 14
	xor	eax, eax
; Line 15
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
; Function compile flags: /Odtp
_b$ = -8						; size = 4
_a$ = -4						; size = 4
?addition@@YIHHH@Z PROC					; addition
; _a$ = ecx
; _b$ = edx
; Line 19
	push	ebp
	mov	ebp, esp
	sub	esp, 8
	mov	DWORD PTR _b$[ebp], edx
	mov	DWORD PTR _a$[ebp], ecx
; Line 20
	mov	eax, DWORD PTR _a$[ebp]
	add	eax, DWORD PTR _b$[ebp]
; Line 21
	mov	esp, ebp
	pop	ebp
	ret	0
?addition@@YIHHH@Z ENDP					; addition
_TEXT	ENDS
END
