; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\JitenderN\REBook\AddNumber\AddNumber\AddNumber.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?addition@@YAHHH@Z				; addition
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_add$ = -4						; size = 4
_main	PROC
; File c:\jitendern\rebook\addnumber\addnumber\addnumber.cpp
; Line 10
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 12
	push	5
	push	4
	call	?addition@@YAHHH@Z			; addition
	add	esp, 8
	mov	DWORD PTR _add$[ebp], eax
; Line 14
	xor	eax, eax
; Line 15
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
; Function compile flags: /Odtp
_a$ = 8						; size = 4
_b$ = 12						; size = 4
?addition@@YAHHH@Z PROC					; addition
; Line 19
	push	ebp
	mov	ebp, esp
; Line 20
	mov	eax, DWORD PTR _a$[ebp]
	add	eax, DWORD PTR _b$[ebp]
; Line 21
	pop	ebp
	ret	0
?addition@@YAHHH@Z ENDP					; addition
_TEXT	ENDS
END
