; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\JitenderN\REBook\scanfWithIntegers\scanfWithIntegers\scanfWithIntegers.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG4678	DB	'Enter a Number: ', 00H
	ORG $+3
$SG4679	DB	'%d', 00H
	ORG $+1
$SG4680	DB	'Number you entered is %d', 0aH, 00H
CONST	ENDS
PUBLIC	_main
EXTRN	_scanf:PROC
EXTRN	_printf:PROC
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_iInput$ = -4						; size = 4
_main	PROC
; File c:\jitendern\rebook\scanfwithintegers\scanfwithintegers\scanfwithintegers.cpp
; Line 7
	push	ecx
; Line 9
	push	OFFSET $SG4678
	call	_printf
; Line 10
	lea	eax, DWORD PTR _iInput$[esp+8]
	push	eax
	push	OFFSET $SG4679
	call	_scanf
; Line 11
	mov	ecx, DWORD PTR _iInput$[esp+16]
	push	ecx
	push	OFFSET $SG4680
	call	_printf
; Line 12
	xor	eax, eax
; Line 13
	add	esp, 24					; 00000018H
	ret	0
_main	ENDP
_TEXT	ENDS
END
