; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\JitenderN\REBook\while\while\while.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG4681	DB	'%d', 0aH, 00H
CONST	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; File c:\jitendern\rebook\while\while\while.cpp
; Line 7
	push	esi
; Line 8
	mov	esi, 1
	npad	10
$LL2@main:
; Line 11
	push	esi
	push	OFFSET $SG4681
	call	_printf
; Line 12
	inc	esi
	add	esp, 8
	cmp	esi, 10					; 0000000aH
	jle	SHORT $LL2@main
; Line 14
	xor	eax, eax
	pop	esi
	ret	0
_main	ENDP
_TEXT	ENDS
END
