; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\JitenderN\REBook\HelloWorld\HelloWorld\HelloWorld.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG4677	DB	'hello, world', 0aH, 00H
CONST	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File c:\jitendern\rebook\helloworld\helloworld\helloworld.cpp
; Line 8
	push	ebp
	mov	ebp, esp
; Line 9
	push	OFFSET $SG4677
	call	_printf
	add	esp, 4
; Line 10
	xor	eax, eax
; Line 11
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
