; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\JitenderN\REBook\Structures\Structures\Structures.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG5660	DB	'Jitender', 00H
	ORG $+3
$SG5662	DB	0aH, '%s %d %llu', 00H
$SG5663	DB	0aH, '%s %d %llu', 00H
CONST	ENDS
PUBLIC	__$ArrayPad$
PUBLIC	_main
EXTRN	_printf:PROC
EXTRN	___security_cookie:DWORD
EXTRN	@__security_check_cookie@4:PROC
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_user$ = -60						; size = 56
__$ArrayPad$ = -4					; size = 4
_main	PROC
; File c:\jitendern\rebook\structures\structures\structures.cpp
; Line 9
	sub	esp, 60					; 0000003cH
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	mov	DWORD PTR __$ArrayPad$[esp+60], eax
; Line 18
	mov	eax, DWORD PTR $SG5660
	mov	ecx, DWORD PTR $SG5660+4
	mov	dl, BYTE PTR $SG5660+8
; Line 22
	push	1
	mov	DWORD PTR _user$[esp+64], eax
	xor	eax, eax
	push	-691168947				; d6cd994dH
	mov	DWORD PTR _user$[esp+77], eax
	mov	DWORD PTR _user$[esp+81], eax
	mov	DWORD PTR _user$[esp+85], eax
	mov	DWORD PTR _user$[esp+89], eax
	mov	DWORD PTR _user$[esp+93], eax
	mov	DWORD PTR _user$[esp+97], eax
	mov	DWORD PTR _user$[esp+101], eax
	mov	WORD PTR _user$[esp+105], ax
	mov	BYTE PTR _user$[esp+107], al
	push	30					; 0000001eH
	lea	eax, DWORD PTR _user$[esp+72]
	push	eax
	push	OFFSET $SG5662
	mov	DWORD PTR _user$[esp+84], ecx
	mov	BYTE PTR _user$[esp+88], dl
	mov	DWORD PTR _user$[esp+120], 30		; 0000001eH
	mov	DWORD PTR _user$[esp+128], -691168947	; d6cd994dH
	mov	DWORD PTR _user$[esp+132], 1
	call	_printf
; Line 23
	mov	ecx, DWORD PTR _user$[esp+132]
	mov	edx, DWORD PTR _user$[esp+128]
	mov	eax, DWORD PTR _user$[esp+120]
	push	ecx
	push	edx
	push	eax
	lea	ecx, DWORD PTR _user$[esp+92]
	push	ecx
	push	OFFSET $SG5663
	call	_printf
; Line 26
	mov	ecx, DWORD PTR __$ArrayPad$[esp+100]
	add	esp, 40					; 00000028H
	xor	ecx, esp
	xor	eax, eax
	call	@__security_check_cookie@4
	add	esp, 60					; 0000003cH
	ret	0
_main	ENDP
_TEXT	ENDS
END
