; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\JitenderN\REBook\SimpleInterestCalculation\SimpleInterestCalculation\SimpleInterestCalculation.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG4681	DB	'%f', 00H
CONST	ENDS
PUBLIC	__real@4059000000000000
PUBLIC	__real@40f00000
PUBLIC	_main
EXTRN	_printf:PROC
EXTRN	__fltused:DWORD
;	COMDAT __real@4059000000000000
; File c:\jitendern\rebook\simpleinterestcalculation\simpleinterestcalculation\simpleinterestcalculation.cpp
CONST	SEGMENT
__real@4059000000000000 DQ 04059000000000000r	; 100
CONST	ENDS
;	COMDAT __real@40f00000
CONST	SEGMENT
__real@40f00000 DD 040f00000r			; 7.5
; Function compile flags: /Odtp
CONST	ENDS
_TEXT	SEGMENT
tv76 = -20						; size = 4
_fInterestAmt$ = -16					; size = 4
_iPrincipalAmt$ = -12					; size = 4
_iNoOfYrs$ = -8						; size = 4
_fSimpleInterest$ = -4					; size = 4
_main	PROC
; Line 7
	push	ebp
	mov	ebp, esp
	sub	esp, 20					; 00000014H
; Line 11
	mov	DWORD PTR _iPrincipalAmt$[ebp], 10000	; 00002710H
; Line 12
	mov	DWORD PTR _iNoOfYrs$[ebp], 5
; Line 13
	fld	DWORD PTR __real@40f00000
	fstp	DWORD PTR _fInterestAmt$[ebp]
; Line 16
	mov	eax, DWORD PTR _iPrincipalAmt$[ebp]
	imul	eax, DWORD PTR _iNoOfYrs$[ebp]
	mov	DWORD PTR tv76[ebp], eax
	fild	DWORD PTR tv76[ebp]
	fmul	DWORD PTR _fInterestAmt$[ebp]
	fdiv	QWORD PTR __real@4059000000000000
	fstp	DWORD PTR _fSimpleInterest$[ebp]
; Line 17
	fld	DWORD PTR _fSimpleInterest$[ebp]
	sub	esp, 8
	fstp	QWORD PTR [esp]
	push	OFFSET $SG4681
	call	_printf
	add	esp, 12					; 0000000cH
; Line 18
	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
