; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\JitenderN\REBook\SimpleInterestCalculation\SimpleInterestCalculation\SimpleInterestCalculation.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG4681	DB	'%f', 00H
CONST	ENDS
PUBLIC	__real@40ad4c0000000000
PUBLIC	_main
EXTRN	_printf:PROC
EXTRN	__fltused:DWORD
;	COMDAT __real@40ad4c0000000000
; File c:\jitendern\rebook\simpleinterestcalculation\simpleinterestcalculation\simpleinterestcalculation.cpp
CONST	SEGMENT
__real@40ad4c0000000000 DQ 040ad4c0000000000r	; 3750
; Function compile flags: /Ogtpy
CONST	ENDS
_TEXT	SEGMENT
_main	PROC
; Line 17
	fld	QWORD PTR __real@40ad4c0000000000
	sub	esp, 8
	fstp	QWORD PTR [esp]
	push	OFFSET $SG4681
	call	_printf
	add	esp, 12					; 0000000cH
; Line 18
	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
END
