; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\JitenderN\REBook\for\for\for.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG4681	DB	'%d', 0aH, 00H
CONST	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_iNumber$ = -4						; size = 4
_main	PROC
; File c:\jitendern\rebook\for\for\for.cpp
; Line 7
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 8
	mov	DWORD PTR _iNumber$[ebp], 1
; Line 9
	mov	DWORD PTR _iNumber$[ebp], 1
	jmp	SHORT $LN3@main
$LN2@main:
	mov	eax, DWORD PTR _iNumber$[ebp]
	add	eax, 2
	mov	DWORD PTR _iNumber$[ebp], eax
$LN3@main:
	cmp	DWORD PTR _iNumber$[ebp], 10		; 0000000aH
	jg	SHORT $LN4@main
; Line 10
	mov	ecx, DWORD PTR _iNumber$[ebp]
	push	ecx
	push	OFFSET $SG4681
	call	_printf
	add	esp, 8
	jmp	SHORT $LN2@main
$LN4@main:
; Line 11
	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
