; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\JitenderN\REBook\ReturningValue\ReturningValue\ReturningValue.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; File c:\jitendern\rebook\returningvalue\returningvalue\returningvalue.cpp
; Line 10
	xor	eax, eax
; Line 11
	ret	0
_main	ENDP
_TEXT	ENDS
PUBLIC	?ReturningValue@@YAHXZ				; ReturningValue
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
?ReturningValue@@YAHXZ PROC				; ReturningValue
; Line 15
	mov	eax, 2020				; 000007e4H
; Line 16
	ret	0
?ReturningValue@@YAHXZ ENDP				; ReturningValue
_TEXT	ENDS
END
