; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\JitenderN\REBook\Pointers\Pointers\Pointers.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG4679	DB	0aH, 'Address of iNumber = 0x%p', 00H
	ORG $+1
$SG4680	DB	0aH, 'Address of iNumber = 0x%p', 00H
	ORG $+1
$SG4681	DB	0aH, 'Address of piNumber = 0x%p', 00H
$SG4682	DB	0aH, 'Value of piNumber = %p', 00H
$SG4683	DB	0aH, 'Value of iNumber = %d', 00H
	ORG $+1
$SG4684	DB	0aH, 'Value of iNumber = %d', 00H
	ORG $+1
$SG4685	DB	0aH, 'Value of iNumber = %d', 00H
CONST	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_piNumber$ = -8						; size = 4
_iNumber$ = -4						; size = 4
_main	PROC
; File c:\jitendern\rebook\pointers\pointers\pointers.cpp
; Line 7
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 8
	mov	DWORD PTR _iNumber$[ebp], 3
; Line 10
	lea	eax, DWORD PTR _iNumber$[ebp]
	mov	DWORD PTR _piNumber$[ebp], eax
; Line 12
	lea	ecx, DWORD PTR _iNumber$[ebp]
	push	ecx
	push	OFFSET $SG4679
	call	_printf
	add	esp, 8
; Line 13
	mov	edx, DWORD PTR _piNumber$[ebp]
	push	edx
	push	OFFSET $SG4680
	call	_printf
	add	esp, 8
; Line 14
	lea	eax, DWORD PTR _piNumber$[ebp]
	push	eax
	push	OFFSET $SG4681
	call	_printf
	add	esp, 8
; Line 15
	mov	ecx, DWORD PTR _piNumber$[ebp]
	push	ecx
	push	OFFSET $SG4682
	call	_printf
	add	esp, 8
; Line 16
	mov	edx, DWORD PTR _iNumber$[ebp]
	push	edx
	push	OFFSET $SG4683
	call	_printf
	add	esp, 8
; Line 17
	mov	eax, DWORD PTR _iNumber$[ebp]
	push	eax
	push	OFFSET $SG4684
	call	_printf
	add	esp, 8
; Line 18
	mov	ecx, DWORD PTR _piNumber$[ebp]
	mov	edx, DWORD PTR [ecx]
	push	edx
	push	OFFSET $SG4685
	call	_printf
	add	esp, 8
; Line 19
	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
