; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\JitenderN\REBook\Pointers\Pointers\Pointers.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG4679	DB	0aH, 'Address of iNumber = 0x%p', 00H
	ORG $+1
$SG4680	DB	0aH, 'Address of iNumber = 0x%p', 00H
	ORG $+1
$SG4681	DB	0aH, 'Address of piNumber = 0x%p', 00H
$SG4682	DB	0aH, 'Value of piNumber = %p', 00H
$SG4683	DB	0aH, 'Value of iNumber = %d', 00H
	ORG $+1
$SG4684	DB	0aH, 'Value of iNumber = %d', 00H
	ORG $+1
$SG4685	DB	0aH, 'Value of iNumber = %d', 00H
CONST	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_iNumber$ = -8						; size = 4
_piNumber$ = -4						; size = 4
_main	PROC
; File c:\jitendern\rebook\pointers\pointers\pointers.cpp
; Line 7
	sub	esp, 8
; Line 10
	lea	eax, DWORD PTR _iNumber$[esp+8]
; Line 12
	mov	ecx, eax
	push	ecx
	push	OFFSET $SG4679
	mov	DWORD PTR _iNumber$[esp+16], 3
	mov	DWORD PTR _piNumber$[esp+16], eax
	call	_printf
; Line 13
	mov	edx, DWORD PTR _piNumber$[esp+16]
	push	edx
	push	OFFSET $SG4680
	call	_printf
; Line 14
	lea	eax, DWORD PTR _piNumber$[esp+24]
	push	eax
	push	OFFSET $SG4681
	call	_printf
; Line 15
	mov	ecx, DWORD PTR _piNumber$[esp+32]
	push	ecx
	push	OFFSET $SG4682
	call	_printf
; Line 16
	mov	edx, DWORD PTR _iNumber$[esp+40]
	push	edx
	push	OFFSET $SG4683
	call	_printf
; Line 17
	mov	eax, DWORD PTR _iNumber$[esp+48]
	push	eax
	push	OFFSET $SG4684
	call	_printf
; Line 18
	mov	ecx, DWORD PTR _piNumber$[esp+56]
	mov	edx, DWORD PTR [ecx]
	push	edx
	push	OFFSET $SG4685
	call	_printf
; Line 19
	xor	eax, eax
	add	esp, 64					; 00000040H
	ret	0
_main	ENDP
_TEXT	ENDS
END
