; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\JitenderN\REBook\ifelse\ifelse\ifelse.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG4679	DB	'Input Number1 : ', 00H
	ORG $+3
$SG4680	DB	'%d', 00H
	ORG $+1
$SG4681	DB	'Input Number2 : ', 00H
	ORG $+3
$SG4682	DB	'%d', 00H
	ORG $+1
$SG4684	DB	'Number1 and Number2 are equal', 0aH, 00H
	ORG $+1
$SG4686	DB	'Number1 and Number2 are not equal', 0aH, 00H
CONST	ENDS
PUBLIC	_main
EXTRN	_scanf:PROC
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_iNumber1$ = -8						; size = 4
_iNumber2$ = -4						; size = 4
_main	PROC
; File c:\jitendern\rebook\ifelse\ifelse\ifelse.cpp
; Line 7
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 10
	push	OFFSET $SG4679
	call	_printf
	add	esp, 4
; Line 11
	lea	eax, DWORD PTR _iNumber1$[ebp]
	push	eax
	push	OFFSET $SG4680
	call	_scanf
	add	esp, 8
; Line 12
	push	OFFSET $SG4681
	call	_printf
	add	esp, 4
; Line 13
	lea	ecx, DWORD PTR _iNumber2$[ebp]
	push	ecx
	push	OFFSET $SG4682
	call	_scanf
	add	esp, 8
; Line 14
	mov	edx, DWORD PTR _iNumber1$[ebp]
	cmp	edx, DWORD PTR _iNumber2$[ebp]
	jne	SHORT $LN2@main
; Line 15
	push	OFFSET $SG4684
	call	_printf
	add	esp, 4
; Line 16
	jmp	SHORT $LN3@main
$LN2@main:
; Line 17
	push	OFFSET $SG4686
	call	_printf
	add	esp, 4
$LN3@main:
; Line 18
	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
