; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\JitenderN\REBook\EmptyFunction\EmptyFunction\EmptyFunction.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; File c:\jitendern\rebook\emptyfunction\emptyfunction\emptyfunction.cpp
; Line 10
	xor	eax, eax
; Line 11
	ret	0
_main	ENDP
_TEXT	ENDS
PUBLIC	?EmptyFunction@@YAXXZ				; EmptyFunction
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
?EmptyFunction@@YAXXZ PROC				; EmptyFunction
; Line 16
	ret	0
?EmptyFunction@@YAXXZ ENDP				; EmptyFunction
_TEXT	ENDS
END
